Update called-codeql-workflow.yml

diff --git a/.github/workflows/called-codeql-workflow.yml b/.github/workflows/called-codeql-workflow.yml
--- a/.github/workflows/called-codeql-workflow.yml
+++ b/.github/workflows/called-codeql-workflow.yml
@@ -53,7 +53,31 @@ jobs:
     - name: Set up jq
       run: sudo apt-get install -y jq
 
-    
+    - name: Find if Open CodeQL vulnerabilities exist
+      env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          OWNER: Reusable-Test  # Replace with the repository owner username
+          REPO: abhi-calling-repo    # Replace with the repository name
+      run: |
+          #!/bin/bash
+
+          set -e  # Exit immediately if a command exits with a non-zero status
+
+          # Function to fetch vulnerabilities
+          fetch_vulnerabilities() {
+            local url="https://api.github.com/repos/${OWNER}/${REPO}/code-scanning/alerts"
+            local result=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" "$url")
+            local open_vulnerabilities=$(echo "$result" | jq '[.[] | select(.state == "open")] | length')
+
+           if [ "$open_vulnerabilities" -gt 0 ]; then
+             echo "Found $open_vulnerabilities open vulnerabilities."
+             exit 1  # Exit with a non-zero status to indicate an error condition
+           else
+             echo "No open vulnerabilities found."
+           fi
+          }
+          # Main script execution
+          fetch_vulnerabilities
     
     # Initializes the CodeQL tools for scanning.
     - name: Initialize CodeQL
